version: 2
updates:
  # Maintain dependencies for Client
  - package-ecosystem: "npm"
    directory: "/apps/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for Server
  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"